GRANT USAGE ON SCHEMA public TO psen_access;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO psen_access;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO psen_access;

/*ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO psen_access;*/


GRANT USAGE ON SCHEMA public TO psen_modify;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO psen_modify;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO psen_modify;


/*ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO psen_modify;*/
