CREATE ROLE PSEN_PROJECT;

GRANT USAGE ON SCHEMA public TO PSEN_PROJECT;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO PSEN_PROJECT;

CREATE ROLE psen_access NOINHERIT;

CREATE ROLE psen_modify NOINHERIT;

GRANT PSEN_PROJECT TO psen_access;
GRANT PSEN_PROJECT TO psen_modify;
